### ISSUE TITLE
CMakeLists.txt files out of date

### ISSUE THREAD

**Issue by rexkerr** [cierelabs/boostache#14]
The CMakeLists.txt files have not been updated since at least 5c1695b when the boost/ folder was removed.

**Comment by jefftrull** [comment]
Thanks Rex!  Is there a specific problem with it?  I've been treating the boost.build flow as "source" and trying to duplicate its functionality, but it's been a while since I checked.

**Comment by rexkerr** [comment]
I'm working on an update now, but the things I see so far are:

* there is a boost/ folder in the root that no longer exists, but is still referenced in the root CMakeLists.txt file.  
* In the examples folder there are four example cpp files... 
    * three of them are mentioned in the Jamfile [one missing, simple_generate2.cpp]
    * none are mentioned in the CMakeLists.txt.  
    * The CMakeLists.txt brings in the company_report folder, but the Jamfile does not
