### ISSUE TITLE
mustache inverted section translation

### ISSUE THREAD

**Issue by burlog** [cierelabs/boostache#7]
Current compiler translates mustache translated section into this tree:

    └──[<if>: lines]
       ├──[<then>]
       │  └──[<undefined>]
       └──[<else>]
          └──[<select>: lines]
             └──[<for_each>: lines]
                └──[<literal>: "there are no items%"]

I think, that it's not right translation due to need of the confusing code in `select_context_dispatch`    function. If there is no key then it have to call `generate` function with *fake* container with one empty entry due to consequent `for_each`. I thing that better (even simply) translation would be this:

    └──[<if>: lines]
       ├──[<then>]
       │  └──[<undefined>]
       └──[<else>]
          └──[<literal>: "there are no items%"]

**Comment by burlog** [comment]
I patch stache_compiler.hp in burlog/boostache@7bb53f0292a1ff3b777a2ae780accf0ce786f4f2

**Comment by mjcaisse** [comment]
The translation from the mustache to internal AST for sections must include the `for_each`. The `for_each` is driven by the data type that is active in the context and is not affected by the template body in the section.

For example,

```
{{#items}}
  foo
{{/items}}
```

with data

```
{
  "items": [1,2,3]
}
```

Will produce output:

```
foo
foo
foo
```

In other words, a section in mustache always compiles to a construct that has a `for_each`.

**Comment by mjcaisse** [comment]
burlog -

I just realized your comment was for inverted sections  (o;  Of course, that is an appropriate optimization and by looking at the history it got removed with the rework of `select_context`.

**Comment by mjcaisse** [comment]
Thanks for the report and patch! Optimized in develop.
